// <auto-generated />
namespace AD_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AdhiChanges2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdhiChanges2));
        
        string IMigrationMetadata.Id
        {
            get { return "202001271022388_AdhiChanges2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
